/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finstere;

import java.util.Arrays;
import java.util.List;

/**
 *
 * @author nKBlaZy
 */
public class Finstere extends javax.swing.JFrame {
    /* Constantes pour les directions */
    public final static int HAUT = 1, BAS = -1, GAUCHE = 2, DROITE = -2;
    /* Constantes pour les types de flaques d'hemoglobine (nom de l'image sans
     * l'extension)
     */
    public final static String CARRE = "tachesang_carree",
            LINEVERT = "tachesang_lineaireH",
            LINEHORI = "tachesang_lineaireV";
    /* Constantes pour les couleurs des personnages */
    public final static String[] COULEURS = {"blue", "brown", "gray", "green",
        "purple", "red", "yellow"};
    /* Constantes pour les valeurs des Carte "une proie" et "deux proies */
    public final static int X = 11, XX = 12;
    /* Constantes pour les coordonnées des Personnage à l'extérieur, sortis, morts */
    public final static int[] EXTERIEUR = {16,10}, SORTI = {-1,0}, MORT = {15, -1};
    /* Partie de Finstere */
    private Partie partie;

    /**
     * Creates new form FinstereFenetre
     */
    public Finstere() {
        initComponents();
        this.newGame.setVisible(true);
    }
    
    /* Retourne true si le _tab est contenu dans _list */
    public static boolean isInList(List<int[]> _list, int[] _tab) {
        for (int[] elem : _list) {
            if (Arrays.equals(elem, _tab)) {
                return true;
            }
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newGame = new javax.swing.JFrame();
        newGamePanel = new javax.swing.JPanel();
        newGameLogo = new javax.swing.JLabel();
        bienvenue = new javax.swing.JLabel();
        newGameTerm = new javax.swing.JButton();
        newGameInterface = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        layeredPanel = new javax.swing.JLayeredPane();
        plateau = new javax.swing.JLabel();
        finstereLogo = new javax.swing.JLabel();
        nbTour = new javax.swing.JLabel();
        nbManche = new javax.swing.JLabel();
        nomJ1 = new javax.swing.JLabel();
        persosJ1 = new javax.swing.JPanel();
        permierJ1 = new javax.swing.JLabel();
        nomJ2 = new javax.swing.JLabel();
        persosJ2 = new javax.swing.JPanel();
        permierJ2 = new javax.swing.JLabel();
        monstreLabel = new javax.swing.JLabel();
        listePioche = new javax.swing.JLabel();
        listeDefausse = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        partieMenu = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        newGame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        newGame.setAlwaysOnTop(true);
        newGame.setLocation(new java.awt.Point(850, 350));
        newGame.setMaximumSize(new java.awt.Dimension(274, 249));
        newGame.setMinimumSize(new java.awt.Dimension(274, 249));
        newGame.setName("Nouvelle Partie"); // NOI18N
        newGame.setPreferredSize(new java.awt.Dimension(274, 239));
        newGame.setResizable(false);
        newGame.setSize(new java.awt.Dimension(274, 249));

        newGamePanel.setBackground(new java.awt.Color(79, 99, 48));
        newGamePanel.setMaximumSize(new java.awt.Dimension(274, 249));
        newGamePanel.setMinimumSize(new java.awt.Dimension(274, 249));
        newGamePanel.setPreferredSize(new java.awt.Dimension(274, 249));

        newGameLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newGameLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_finstere.gif"))); // NOI18N
        newGameLogo.setPreferredSize(new java.awt.Dimension(256, 65));

        bienvenue.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bienvenue.setForeground(new java.awt.Color(254, 248, 120));
        bienvenue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bienvenue.setText("<html><body style='text-align: center'>Bienvenue sur Finstere Flure,<br/>le jeu qui va vous faire frissonner !!!</html>");
        bienvenue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bienvenue.setPreferredSize(new java.awt.Dimension(256, 30));

        newGameTerm.setBackground(java.awt.Color.darkGray);
        newGameTerm.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        newGameTerm.setForeground(new java.awt.Color(254, 248, 120));
        newGameTerm.setText("Nouvelle Partie dans le terminal");
        newGameTerm.setMaximumSize(new java.awt.Dimension(256, 31));
        newGameTerm.setMinimumSize(new java.awt.Dimension(256, 31));
        newGameTerm.setPreferredSize(new java.awt.Dimension(256, 31));
        newGameTerm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newGameTermMouseClicked(evt);
            }
        });

        newGameInterface.setBackground(java.awt.Color.darkGray);
        newGameInterface.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        newGameInterface.setForeground(new java.awt.Color(254, 248, 120));
        newGameInterface.setText("Nouvelle Partie avec interface");
        newGameInterface.setMaximumSize(new java.awt.Dimension(256, 31));
        newGameInterface.setMinimumSize(new java.awt.Dimension(256, 31));
        newGameInterface.setPreferredSize(new java.awt.Dimension(256, 31));

        javax.swing.GroupLayout newGamePanelLayout = new javax.swing.GroupLayout(newGamePanel);
        newGamePanel.setLayout(newGamePanelLayout);
        newGamePanelLayout.setHorizontalGroup(
            newGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newGamePanelLayout.createSequentialGroup()
                .addGroup(newGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newGamePanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(newGameLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newGamePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(newGameTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newGamePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(newGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bienvenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newGameInterface, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        newGamePanelLayout.setVerticalGroup(
            newGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newGamePanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(newGameLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(bienvenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(newGameTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(newGameInterface, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout newGameLayout = new javax.swing.GroupLayout(newGame.getContentPane());
        newGame.getContentPane().setLayout(newGameLayout);
        newGameLayout.setHorizontalGroup(
            newGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newGamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 268, Short.MAX_VALUE)
        );
        newGameLayout.setVerticalGroup(
            newGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newGamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Finstere Flure");
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(79, 99, 48));

        layeredPanel.setPreferredSize(new java.awt.Dimension(694, 479));

        plateau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fns_plateau.jpg"))); // NOI18N

        layeredPanel.setLayer(plateau, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layeredPanelLayout = new javax.swing.GroupLayout(layeredPanel);
        layeredPanel.setLayout(layeredPanelLayout);
        layeredPanelLayout.setHorizontalGroup(
            layeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layeredPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(plateau)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layeredPanelLayout.setVerticalGroup(
            layeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layeredPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(plateau)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        finstereLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        finstereLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_finstere.gif"))); // NOI18N
        finstereLogo.setPreferredSize(new java.awt.Dimension(201, 65));

        nbTour.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        nbTour.setForeground(new java.awt.Color(254, 248, 120));
        nbTour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nbTour.setText("Tour n°1");
        nbTour.setPreferredSize(new java.awt.Dimension(201, 16));

        nbManche.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        nbManche.setForeground(new java.awt.Color(254, 248, 120));
        nbManche.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nbManche.setText("Manche n°1");
        nbManche.setPreferredSize(new java.awt.Dimension(201, 16));

        nomJ1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        nomJ1.setForeground(new java.awt.Color(254, 248, 120));
        nomJ1.setText("Joueur 1");

        persosJ1.setPreferredSize(new java.awt.Dimension(174, 39));
        persosJ1.setLayout(new javax.swing.BoxLayout(persosJ1, javax.swing.BoxLayout.LINE_AXIS));

        permierJ1.setPreferredSize(new java.awt.Dimension(21, 35));

        nomJ2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        nomJ2.setForeground(new java.awt.Color(254, 248, 120));
        nomJ2.setText("Joueur 2");

        persosJ2.setPreferredSize(new java.awt.Dimension(174, 39));
        persosJ2.setLayout(new javax.swing.BoxLayout(persosJ2, javax.swing.BoxLayout.LINE_AXIS));

        permierJ2.setPreferredSize(new java.awt.Dimension(21, 35));

        monstreLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        monstreLabel.setForeground(new java.awt.Color(254, 248, 120));
        monstreLabel.setText("Monstre");

        listePioche.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        listePioche.setForeground(new java.awt.Color(254, 248, 120));
        listePioche.setText("Pioche : 8 cartes (5 7 7 8 8 10 X XX)");

        listeDefausse.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        listeDefausse.setForeground(new java.awt.Color(254, 248, 120));
        listeDefausse.setText("Défausse : 0 cartes ()");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(layeredPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(finstereLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nbManche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nbTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomJ1)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(persosJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(permierJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomJ2)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(persosJ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(permierJ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(monstreLabel))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(listePioche))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(listeDefausse)))
                .addContainerGap(353, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(layeredPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(finstereLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(nbTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(nbManche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(nomJ1)
                        .addGap(6, 6, 6)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(persosJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(permierJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addComponent(nomJ2)
                        .addGap(6, 6, 6)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(persosJ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(permierJ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(monstreLabel)
                        .addGap(6, 6, 6)
                        .addComponent(listePioche)
                        .addGap(6, 6, 6)
                        .addComponent(listeDefausse)))
                .addContainerGap(202, Short.MAX_VALUE))
        );

        partieMenu.setText("Partie");
        menuBar.add(partieMenu);

        jMenu2.setText("Edit");
        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void newGameTermMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newGameTermMouseClicked
        this.newGame.setVisible(false);
        this.setVisible(false);
        this.partie = new Partie(this, true);
        this.partie.initPartie();
        this.partie.jouer();
    }//GEN-LAST:event_newGameTermMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Finstere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Finstere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Finstere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Finstere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Finstere().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bienvenue;
    private javax.swing.JLabel finstereLogo;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JLayeredPane layeredPanel;
    private javax.swing.JLabel listeDefausse;
    private javax.swing.JLabel listePioche;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel monstreLabel;
    private javax.swing.JLabel nbManche;
    private javax.swing.JLabel nbTour;
    private javax.swing.JFrame newGame;
    private javax.swing.JButton newGameInterface;
    private javax.swing.JLabel newGameLogo;
    private javax.swing.JPanel newGamePanel;
    private javax.swing.JButton newGameTerm;
    private javax.swing.JLabel nomJ1;
    private javax.swing.JLabel nomJ2;
    private javax.swing.JMenu partieMenu;
    private javax.swing.JLabel permierJ1;
    private javax.swing.JLabel permierJ2;
    private javax.swing.JPanel persosJ1;
    private javax.swing.JPanel persosJ2;
    private javax.swing.JLabel plateau;
    // End of variables declaration//GEN-END:variables
}
